### PR TITLE
Removed reference to "Open Farm Game" in welcome template.

### PR DESCRIPTION
**Pull request by madbob**
The website do not longer exists.

### CODE REVIEW

**Comment by jankusanagi** [comment]
Thanks for your help!
openfarmgame.com is up and running at the moment. Maybe there was a glitch, but it's fine now.

BTW, you seem to be mixing commits for other things in this same PR.

**Comment by madbob** [comment]
Ok, fine. I just got turbated by the apparently death link.

About the other two patch, I've just splitted them in different pull requests. I made some confusion with branches :-P

**Comment by ansorg** [comment]
openfarmgame seems dead now (unless spam, advertisement was the intention?), better remove it as planned?

**Comment by vxcamiloxv** [comment]
@ansorg  you have the reason.

**Comment by Serkan-devel** [comment]
What happened to the creator?

**Comment by vxcamiloxv** [comment]
The creator is fine, still alive but the domain no.

**Comment by Serkan-devel** [comment]
But is the project source code still available?  Maybe it can be hosted statically on github pages or neocities on a new domain

**Comment by vxcamiloxv** [comment]
@Serkan-devel  https://github.com/e14n/openfarmgame

**Pull request closed without merging**
