### PR TITLE
Defang fix

### PR DESCRIPTION
**Pull request by profOnno**
Issue referenced and fixed by [jlord](http://github/jlord)

### CODE REVIEW

**Comment by strugee** [comment]
@profOnno the app code looks good (I'm assuming you tested it locally?) but I'm a little confused as to why there's an entire file being added. Was there just no test for the sanitization before? That doesn't seem correct...

**Comment by strugee** [comment]
@profOnno so I think it'd be better if the tests were in `scrubber-activity-api-test.js`. Other than that, though, this looks great :)

Thanks as always!

**Comment by strugee** [comment]
I went ahead and moved the test myself, since we were getting complaints on the network about this (https://io.jrobb.org/jrobb/note/4my4TsXqTlOV32LylnrhFQ). Thanks, @profOnno!

**Comment by jfrobbins** [comment]
Thanks!

On May 3, 2016 2:15:50 PM EDT, Alex Jordan <notifications@github.com> wrote:
>I went ahead and moved the test myself, since we were getting
>complaints on the network about this
>(https://io.jrobb.org/jrobb/note/4my4TsXqTlOV32LylnrhFQ). Thanks,
>@profOnno!
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e14n/pump.io/pull/1144#issuecomment-216617795

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by strugee** [comment]
@jfrobbins sure.

**Pull request merged**
