### PR TITLE
Added support for showing video objects in the web interface.

### PR DESCRIPTION
**Pull request by stephensekula**
This is a first simple modification to some of the UTML files to allow support for video objects in the web interface. This could be a useful addition to the base. If you have suggestions for making this more robust before including it in the base, let me know. I'm happy to implement the suggestions.

### CODE REVIEW

**Comment by jankusanagi** [comment]
Cool!

In major-activity.utml, the video src parameter should check for ProxyURL's just like the image src does a couple of lines above (object.image.pump_io && object.image.pump_io.proxyURL), and use that if present, instead of the regular stream.url parameter.

Otherwise non-public videos posted by people in another server can't be played.


I don't know why the image code in object.utml doesn't account for proxyURLs, but I guess there's nothing to change there.


Great job!
Cheers! \o/

**Comment by stephensekula** [comment]
Just so this is closed, I followed your advice and committed code using proxyURLs.

**Comment by strugee** [comment]
@stephensekula can you rebase this on top of current `master`? This will allow Travis to run with fixed tests.

**Comment by strugee** [comment]
Continued in a new PR

**Pull request closed without merging**
